# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

name: Keep clone up to date
variables:
  REMOTE_ADDR: 'https://github.com/AlekWithK/BuildManager'
stages:
  - stage: running_git_commands
    displayName: running_git_commands
    jobs:
      - job: initiate
        displayName: initiate
        continueOnError: false
        steps:
        - checkout: self
          clean: true
          persistCredentials: true
          displayName: run_commands
        - bash: | 
            git checkout main
            git remote add repoGithub $(REMOTE_ADDR)
            git fetch BuildManager main
            git reset --hard BuildManager/main
            git pull --rebase BuildManager main
            git push -f origin